branches:
  only:
  - master

sudo: required
dist: trusty
language: cpp

matrix:
  include:
    # GCC5 on Linux
    - os: linux
      script: 
        - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
        - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # Clang on OSX
    - os: osx
      osx_image: xcode9.2

before_install:
  - eval "${MATRIX_EVAL}"

before_script:

script: 
  - make


